version: '3.8'

services:
  redis:
    image: redis:alpine
  web:
    build: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
